name = input('Your name: ')
print('Oh,hi', name)
print('but I think the name pigky is more suitable for u')
print('Also, I think...')
print('Cathy is more beautiful than u')
input('What is your weight? ')
print('Omg!! u 1835288 kg?!!')
print('WoW, u so fat!')
print('The most beautiful girl in the world that called Cathy just has 30 kg')
print('ummmmm... so why u so fat? ')
print('u see see u')
print('one day day')
print('just only eat eat eat')
print('u see see your fat!!!')
print('And u did not keep fit!!!')
print('Omg so fat lol')
print('oh sorry, I cannot chat with u la')
print('because i think u will say SIE DING')
print('and then i will die')
print('so bye~')
print('see u later~')